### PR TITLE
Use webpack for module bundling

### PR DESCRIPTION
**Pull request by icewind1991**
Big monolithic js code makes me sad every time I have to touch it.

@MorrisJobke can you add the `build` directory to the transifex exclude list.

Adds webpack+babel for module bundling/transpiling allowing for

- easier to split code over multiple files
- cleaner js using modern js features
- small minified output
- slightly less ugly way to lazy load ace editor modes with our csp
- as a bonus, the changed way of loading ace enables the more advanced code inspection features ace provides:
    ace code inspection

Building the project is a simple `make` (documented in `contributing.md`)

Will do some more code cleanup in a follow up PR

Also changed to maintainer to someone who actually touched the code recently.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Moved to 14.

**Comment by MorrisJobke** [comment]
Moved to 15

**Comment by MorrisJobke** [comment]
Let's move this to 16.

**Comment by juliushaertl** [comment]
@rullzer @icewind1991 I rebased this and also moved ace to a separate chunk, so we now just load around 18kb instead of 660kb

**Comment by rullzer** [comment]
Ah seems that this dow break the markdown editor :disappointed:

**Comment by rullzer** [comment]
ah it helps if I build it of course.
However I do get 400 errors when updating a .md file. Let me dive into that.

**Comment by rullzer** [comment]
> However I do get 400 errors when updating a .md file. Let me dive into that.

glitch I guess. Works as advertised.

**Comment by icewind1991** [comment]
did some quick testing and all works as expected :+1:

**Pull request merged**
