### PR TITLE
Add webpack build to drone

### LINKED ISSUE #167: Add check for bundles
Aparently we don't check if the bundled files are up to date. Encountered because https://github.com/nextcloud/files_texteditor/pull/164 is not working in the release as the bundles were not updated.

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #167

### CODE REVIEW

**Comment by juliushaertl** [comment]
I cannot enable drone for the repo. @MorrisJobke Do you have an idea why?

**Comment by juliushaertl** [comment]
@MorrisJobke the repo is still not activatable in drone :/

**Comment by MorrisJobke** [comment]
> @MorrisJobke the repo is still not activatable in drone :/

I just clicked "activate" ... mind to test again?

**Comment by juliushaertl** [comment]
Ok, seems to be active now. Not sure why that didn't work for me :woman_shrugging:

**Pull request merged**
