### PR TITLE
Update ace editor from 1.2.5 to 1.2.8

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/nextcloud/files_texteditor/issues/44

See https://github.com/ajaxorg/ace/blob/master/ChangeLog.txt for all upstream changes

### CODE REVIEW

**Comment by icewind1991** [comment]
@Acris can you verify if this fixes the problem for you

**Comment by Acris** [comment]
@icewind1991 Hi, I got the anwser from https://github.com/postmanlabs/postman-app-support/issues/2530#issuecomment-312193592. As I known, GitLab has the same bug in some version, and I found GitLab use Ace editor too. So I think this bug is from ace editor and they fixed it on 2016. :-)

**Comment by nickvergessen** [comment]
@Acris  you can download the package here https://github.com/nextcloud/files_texteditor/archive/ace-1.2.8.zip

and then simply replace your apps/files_texteditor/ folder with the one from the zip

**Comment by nickvergessen** [comment]
I checked out the branch and could still type. However I don't know how to get the thing to actually show up and do something. Any steps on that?

**Comment by Acris** [comment]
@nickvergessen Hello, I replaced `apps/files_texteditor/` folder and tried to type some Chinese, and this bug has been fixed, so this is correct way :)

This is my test site:
[http://45.32.50.16:8888](http://45.32.50.16:8888)
username and password:
`test / test`

**Comment by nickvergessen** [comment]
When I type `zhong` the thing does not pop up thou, do I need to install something additionally or set my OS to chinese or something?

**Comment by Acris** [comment]
@nickvergessen You should install a Chinese input method. What OS do you use? If you use macOS or Windows, you can add it from Settings, don't  need install 3rd input method.

**Comment by nickvergessen** [comment]
Linux mint (ubuntu based)

**Comment by Acris** [comment]
@nickvergessen OK, for Linux Mint, you can install fcitx-rime by `apt-get install fcitx-rime`.

**Comment by Acris** [comment]
I closed the test site. If needed, I'll re-open it.

**Pull request merged**
