### PR TITLE
Bump frontend dependencies and fix container name

### PR DESCRIPTION
**Pull request by juliushaertl**
- Bump webpack
- Rename editor container to avoid conflicts
- Remove committed bundles since the app is not shipped anymore

### CODE REVIEW

**Comment by rullzer** [comment]
>     * Bump webpack
> 
>     * Rename editor container to avoid conflicts
> 
>     * Remove committed bundles since the app is not shipped anymore

It is shipped...

**Comment by juliushaertl** [comment]
Not any more, this is the legacy text editor. The plan was to build an appstore release so users can continue using the old one if preferred.

**Comment by rullzer** [comment]
I stupid me. Yes sure

**Comment by juliushaertl** [comment]
@rullzer Mind to give your :+1: ? :grin:

**Pull request merged**
