### PR TITLE
Make NewLine auto

### LINKED ISSUE #156: Editing converts line endings to CR LF
### Summary

Editing a .md file in the markdown editor automatically converts all line ending to Windows style (CR LF), even if the file is using Unix-style (LF only) line endings. Instead, the editor should analyze the file to find out which style it's using, create new lines with that style, and leave everything else unchanged.

To understand why the present behaviour is a problem, put a big Unix-style .md file into a git repo, put the repo into your Nextcloud, edit the file with the markdown editor, and then do "git diff".

(I originally reported this to the files_markdown repo (https://github.com/icewind1991/files_markdown/issues/125). Was told it belongs here instead.)

### Steps to reproduce
1. Create a text file with Unix line endings (LF only) in your Nextcloud.
2. Open the file in the app.
3. Insert a single character.
4. Wait until the app auto-saves the file.

### Expected behaviour
The line endings in the file should still be LF only.

### Actual behaviour
All line endings are converted to Windows style (CR LF).

### Server configuration

**Operating system**:
Lubuntu

**Web server:**
nginx

**Database:**
MariaDB

**PHP version:**
Don't know but I don't think it matters

**Nextcloud version:** (see Nextcloud admin page)
15

**Where did you install Nextcloud from:**
Internet

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Vivaldi, Chromium, Safari

**Operating system:**
macOS, Linux

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

### PR DESCRIPTION
**Pull request by ionum**
Resolves #156

### CODE REVIEW

**Comment by tavinus** [comment]
Hi. 
Is this on hold just because of the signing or does it have any other issue?
The way I see is that "windows" can cause corruption on *nix code files, right?
Not sure if there are any issues on using 'auto' though, and what would be the default for new files.

**Comment by ifuchs** [comment]
I tried changing line 448 to say "auto" rather than "windows" but when I edit a file that is in unix format, it is still adding /r to the end of each line.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Changing manually will not work since the javascript files are bundled with webpack, so you would need to clone the app from the git repo and run make to build it with the change.

**Comment by juliushaertl** [comment]
Could you add a signoff message to your commit?

https://github.com/nextcloud/files_texteditor/pull/197/checks?check_run_id=407313854

**Comment by ionum** [comment]
Done

**Pull request merged**
